### ISSUE TITLE
ReferenceError on Travis CI Build (Node 11.x)

### ISSUE THREAD

**Issue by LucasCarrias** [brazilian-utils/brazilian-utils#241]
I'm getting the following error at the Node v11 Travis CI build:

```
> npm run build

> @brazilian-utils/brazilian-utils@1.0.0-rc.12 prebuild /home/travis/build/LucasCarrias/brazilian-utils

> npm run update-cities

> @brazilian-utils/brazilian-utils@1.0.0-rc.12 update-cities /home/travis/build/LucasCarrias/brazilian-utils

> node scripts/getCitiesFromIBGE.js && prettier --write ./src/common/cities.ts

/home/travis/build/LucasCarrias/brazilian-utils/node_modules/prettier/index.js:35440

var queueMicrotask_1 = typeof queueMicrotask === 'function' ? queueMicrotask.bind(globalThis) // reuse resolved promise, and allocate it lazily
                                                                                
ReferenceError: globalThis is not defined

    at Object.<anonymous> (/home/travis/build/LucasCarrias/brazilian-utils/node_modules/prettier/index.js:35440:83)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/travis/build/LucasCarrias/brazilian-utils/node_modules/prettier/bin-prettier.js:131:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
```

This error seems to be triggered by the `prettier --write ./src/common/cities.ts` call.

One possible workaround is to update the [.travis.yml](https://github.com/brazilian-utils/brazilian-utils/blob/main/.travis.yml) Node build versions to the same versions as the GitHub's Workflows [build.yml](https://github.com/brazilian-utils/brazilian-utils/blob/main/.github/workflows/build.yml) Node version. As far as I've checked, Node 10.x doesn't breaks the Travis build.

**Comment by hyanmandian** [comment]
Closed by #242
